### ISSUE TITLE
Compiling on OSX

### ISSUE THREAD

**Issue by blitmaps** [OneLoneCoder/olcPixelGameEngine#44] opened 2019-09-07 20:00 UTC
I did this to compile on OSX and it worked perfectly. OSX 10.14.6 (18G95)

/usr/local/bin/g++-9 -o olcExample olcExampleProgram.cpp -L/opt/X11/lib -lX11 -lGL -lpthread -lpng -framework OpenGL -I/opt/X11/include

g++ was installed through brew (clang fails)

I didn't submit a pull on documentation, didn't want to assume how you wanted it.

**Comment by blitmaps** [comment] 2019-09-17 09:36
@davidsummers this worked perfectly for me.

**Comment by nfoste82** [comment] 2019-09-20 03:05
I'm able to compile it, but when I run it all I get is a seg fault with no callstack.

[1]    6544 segmentation fault  ./olcExampleProgram

Best I can tell is that it's happening somewhere inside of the call to olc_WindowCreate()

**Comment by blitmaps** [comment] 2019-09-20 06:35
@nfoste82, I'd be tempted to list your configuration and move this to a new ticket - if there is a fault in olc_WindowCreate, it will probably be crossplatform.

**Comment by Stephan-G** [comment] 2019-10-07 11:01
Same here. The segmentation fault is caused by not being able to get a display. It's probably an access right issue. To quickly fix it, run things from a terminal launched by xquartz. That worked for me, at least removing the seg fault. It's still not creating a window though and the `start` method returns 0. To get things rolling, I've switched to a VM running Ubuntu.

**Comment by OneLoneCoder** [comment] 2019-10-12 18:36
Hi Guys, I'm interested in getting mac support officially added to the header file, so thanks for this information.

**Comment by tliu0c** [comment] 2020-02-12 23:25
How about Linux support?

**Comment by OneLoneCoder** [comment] 2020-02-13 08:27
It builds on linux. Lol it was originally developed on linux 😁 the linux build instructions are in the header file.

**Comment by Balint66** [comment] 2020-04-18 16:26
I'm just here to give my one cent to the community.

[Darling](https://github.com/darlinghq/darling) is a MacOS emulation layer for linux and it's not so bad.

Right now they are working on the UIKit implementation but basic UI apps are working.

I think you could have a look at it @OneLoneCoder, it won't hurt and maybe you'd be able to test out things. I know it's not as good as having a mac that you can test on but it's better than nothing. :)

**Comment by OneLoneCoder** [comment] 2020-05-04 15:02
Since there is an up to date Mac port now, i'm closing this

**Closed by OneLoneCoder** 2020-05-04 15:02 UTC
